import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <div 
    className='bg-gradient-to-t from-green-100 to-blue-300'
    >
      <Head>
        <title>Donate to Nyx</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='grid justify-center drop-shadow-xl'><Image src="/LOGO.png" width={500} height={300} /></header>

      <main className='font-Nanum grid justify-center py-4'>


        <div className="container mx-auto px-4 grid justify-center text-center font-Nanum">
          <div className="max-w-sm w-full lg:max-w-full lg:flex justify-center">
            <div className="h-auto md:h-auto lg:h-auto lg:w-48 flex-none bg-cover drop-shadow-xl rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden" >
            <Image width={400} height={600} src='/nyx-paint.png' className=''/>

            </div>
            <div className="border-r border-b border-l border-gray-400 lg:border-l-0 lg:border-t lg:border-gray-400 bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal">
              <div className="mb-8">
                <div className="text-gray-900 font-bold text-xl mb-2 uppercase font-bold">Nyx</div>
                <p className="text-gray-700 text-base">
                  Nyx is my baby girl and she needs help. Over the holidays Nyx unfortanetely tore her ACL and is in serious pain. She requires a surgey that is rather expensive but without will cause serious issues down the line; arthritis, joint pain, lameness, sweliing and could even develop bone spurs. Please help with any amount you can. Thank you all so much!
                </p>
              </div>
              <div className="flex items-center">
                <div className="text-sm">
                  <p className="text-gray-900 leading-none">Mary Jenkin</p>
                </div>
              </div>
            </div>
          </div>
          </div>
        <h1 className="uppercase font-bold leading-snug text-center text-black text-l py-3">
          Please help this Pup get the care that she Needs
        </h1>

        <div className='py-10 grid justify-center'>
        <button class="rounded-full ... shadow-xl p-3 bg-green-500">Donate Now</button>
        </div>

      </main>
    </div>
  )
}
